sudo: required

services:
  - docker

branches:
  only:
    - master

before_install:
  - docker build -t ros_test_xenial -f dockerfile.xenial .

script: 
  - docker run --rm -t ros_test_xenial /home/test_user/script_setup.sh 
